### ISSUE TITLE
# 提示：无法打开指定dll库的“Wmcode.dll”中的loadWMFromBuffer函数

### ISSUE THREAD

**Issue by blossomnoodles** [WithHades/HFUT#1]
如题
系统 win10 64位
网络环境：校园网
未安装查毒软件
![default](https://user-images.githubusercontent.com/22489650/39966644-e5b8d3c0-56e1-11e8-9f69-c652eadaf807.PNG)

**Comment by WithHades** [comment]
emmmm请尝试关闭杀毒软件，然后重新运行该程序。
