### ISSUE TITLE
想知道简单的宏观实现机理

### ISSUE THREAD

**Issue by wolfdan666** [WithHades/HFUT#13]
十分感谢大佬学长，虽然  现代礼仪  这门课很有价值，但是自己最近实在是没有时间，幸好有大佬学长写的东西，感谢

还想知道学长这个实现的大概机理是什么？是先试错吗？还是爬取解析整个数据库了？

**Comment by WithHades** [comment]
已经更新到github

**Comment by ODChen** [comment]
>           已经更新到github
学长辛苦了，那请问学长现在有稍微能用的版本吗，哪怕有点bug，因为明天就截止了

**Comment by WithHades** [comment]
hh用半天按照我的思路爬一个题库出来就ojbk了

**Comment by ODChen** [comment]
>           hh用半天按照我的思路爬一个题库出来就ojbk了

我死了，明天就截止了，我的python刚入门...
